#!/bin/sh

# first we set some variables
NAME=`whoami`
PROGRAM=/usr/local/gromos-0915/bin/md_mpi
SIMULDIR=/home/arenevey/ex3-test/eq

# create temporary directory
WORKDIR=${SIMULDIR}
mkdir -p ${WORKDIR}
cd       ${WORKDIR}

# set the input files
TOPO=${SIMULDIR}/../topo/protein.top
IUNIT=${SIMULDIR}/protein_1.imd
INPUTCRD=${SIMULDIR}/protein_box_min.cnf
REFPOS=${SIMULDIR}/protein_box_min.rpr
POSRESSPEC=${SIMULDIR}/protein_box_min.por

#set the output files
OUNIT=protein_1.omd
OUTPUTCRD=protein_1.cnf
OUTPUTTRX=protein_1.trc
OUTPUTTRE=protein_1.tre


MDOK=1

mpirun ${PROGRAM} \
	@topo        ${TOPO} \
	@conf        ${INPUTCRD} \
	@input       ${IUNIT} \
	@posresspec  ${POSRESSPEC} \
	@refpos      ${REFPOS} \
	@fin         ${OUTPUTCRD} \
	@trc         ${OUTPUTTRX} \
	@tre         ${OUTPUTTRE}\
	>            ${OUNIT}
grep "finished successfully" ${OUNIT} > /dev/null || MDOK=0

uname -a >> ${OUNIT}

# compress some files
gzip ${OUTPUTTRX}
gzip ${OUTPUTTRE}

# copy the files back
OK=1
cp ${OUNIT}               ${SIMULDIR} || OK=0
cp ${OUTPUTCRD}           ${SIMULDIR} || OK=0
cp ${OUTPUTTRX}.gz        ${SIMULDIR} || OK=0
cp ${OUTPUTTRE}.gz        ${SIMULDIR} || OK=0

# clean up after successful run
if `test ${OK} -eq 0`; then
  uname -a > mess;
  echo 'cp failed for protein, run 1' >> mess;
  Mail -s "ERROR" ${NAME} < mess;
  cd ${SIMULDIR};
else
  cd ${SIMULDIR};
  rm ${WORKDIR}/*;
  rmdir ${WORKDIR};
fi

# stop if MD was not succesfull
if `test ${MDOK} -eq 0`; then
  exit
fi

# perform last command (usually submit next job)
cd ${SIMULDIR}
qsub -N protein_2 -cwd -j y -o protein_2 -pe orte 4 ./protein_2.run 
