#!/bin/sh

# first we set some variables
NAME=`whoami`
PROGRAM=/usr/local/gromos-0614/bin/md_mpi
SIMULDIR=/home/weihuang/ex6/eq

# create temporary directory
WORKDIR=${SIMULDIR}
mkdir -p ${WORKDIR}
cd       ${WORKDIR}

# set the input files
TOPO=${SIMULDIR}/../topo/peptide.top
IUNIT=${SIMULDIR}/eq_peptide_2.imd
INPUTCRD=${SIMULDIR}/eq_peptide_1.cnf
REFPOS=${SIMULDIR}/../box/peptide_H2O.rpr
POSRESSPEC=${SIMULDIR}/../box/peptide_H2O.por

#set the output files
OUNIT=eq_peptide_2.omd
OUTPUTCRD=eq_peptide_2.cnf
OUTPUTTRX=eq_peptide_2.trc
OUTPUTTRE=eq_peptide_2.tre


MDOK=1

mpirun ${PROGRAM} \
	@topo        ${TOPO} \
	@conf        ${INPUTCRD} \
	@input       ${IUNIT} \
	@posresspec  ${POSRESSPEC} \
	@refpos      ${REFPOS} \
	@fin         ${OUTPUTCRD} \
	@trc         ${OUTPUTTRX} \
	@tre         ${OUTPUTTRE}\
	>            ${OUNIT}
grep "finished successfully" ${OUNIT} > /dev/null || MDOK=0

uname -a >> ${OUNIT}

# compress some files
gzip ${OUTPUTTRX}
gzip ${OUTPUTTRE}

# copy the files back
OK=1
cp ${OUNIT}               ${SIMULDIR} || OK=0
cp ${OUTPUTCRD}           ${SIMULDIR} || OK=0
cp ${OUTPUTTRX}.gz        ${SIMULDIR} || OK=0
cp ${OUTPUTTRE}.gz        ${SIMULDIR} || OK=0

# clean up after successful run
if `test ${OK} -eq 0`; then
  uname -a > mess;
  echo 'cp failed for eq_peptide, run 2' >> mess;
  Mail -s "ERROR" ${NAME} < mess;
  cd ${SIMULDIR};
else
  cd ${SIMULDIR};
  rm ${WORKDIR}/*;
  rmdir ${WORKDIR};
fi

# stop if MD was not succesfull
if `test ${MDOK} -eq 0`; then
  exit
fi

# perform last command (usually submit next job)
cd ${SIMULDIR}
qsub -N eq_peptide_3 -cwd -j y -o eq_peptide_3 -pe orte 4 ./eq_peptide_3.run 
