#!/bin/sh

# first we set some variables
NAME=`whoami`
PROGRAM=/usr/local/gromos-0915/bin/md_mpi
SIMULDIR=/home/poborsky/newex6/md/unrestrained

# create temporary directory
WORKDIR=${SIMULDIR}
mkdir -p ${WORKDIR}
cd       ${WORKDIR}

# set the input files
TOPO=${SIMULDIR}/../../topo/peptide.top
IUNIT=${SIMULDIR}/md_unrestrained_46.imd
INPUTCRD=${SIMULDIR}/md_unrestrained_45.cnf

#set the output files
OUNIT=md_unrestrained_46.omd
OUTPUTCRD=md_unrestrained_46.cnf
OUTPUTTRX=md_unrestrained_46.trc
OUTPUTTRE=md_unrestrained_46.tre


MDOK=1

mpirun ${PROGRAM} \
	@topo        ${TOPO} \
	@conf        ${INPUTCRD} \
	@input       ${IUNIT} \
	@fin         ${OUTPUTCRD} \
	@trc         ${OUTPUTTRX} \
	@tre         ${OUTPUTTRE}\
	>            ${OUNIT}
grep "finished successfully" ${OUNIT} > /dev/null || MDOK=0

uname -a >> ${OUNIT}

# compress some files
gzip ${OUTPUTTRX}
gzip ${OUTPUTTRE}

# copy the files back
OK=1
cp ${OUNIT}               ${SIMULDIR} || OK=0
cp ${OUTPUTCRD}           ${SIMULDIR} || OK=0
cp ${OUTPUTTRX}.gz        ${SIMULDIR} || OK=0
cp ${OUTPUTTRE}.gz        ${SIMULDIR} || OK=0

# clean up after successful run
if `test ${OK} -eq 0`; then
  uname -a > mess;
  echo 'cp failed for md_unrestrained, run 46' >> mess;
  Mail -s "ERROR" ${NAME} < mess;
  cd ${SIMULDIR};
else
  cd ${SIMULDIR};
  rm ${WORKDIR}/*;
  rmdir ${WORKDIR};
fi

# stop if MD was not succesfull
if `test ${MDOK} -eq 0`; then
  exit
fi

# perform last command (usually submit next job)
cd ${SIMULDIR}
qsub -N md_unrestrained_47 -cwd -j y -o md_unrestrained_47 -pe orte 4 ./md_unrestrained_47.run 
