#!/bin/sh

# first we set some variables
NAME=`whoami`
PROGRAM=/cluster/work/igc/CSBMS/GROMOS/gromosXX/bin/md
SIMULDIR=/cluster/home/jbachmann/ex6/md/unrestrained

# create temporary directory
WORKDIR=${TMPDIR}/${SIMULDIR}/running
mkdir -p ${WORKDIR}
cd       ${WORKDIR}

# set the input files
TOPO=${SIMULDIR}/../../topo/peptide.top
IUNIT=${SIMULDIR}/md_unrestrained_4.imd
INPUTCRD=${SIMULDIR}/md_unrestrained_3.cnf

#set the output files
OUNIT=md_unrestrained_4.omd
OUTPUTCRD=md_unrestrained_4.cnf
OUTPUTTRX=md_unrestrained_4.trc
OUTPUTTRE=md_unrestrained_4.tre


MDOK=1

${PROGRAM} \
	@topo        ${TOPO} \
	@conf        ${INPUTCRD} \
	@input       ${IUNIT} \
	@fin         ${OUTPUTCRD} \
	@trc         ${OUTPUTTRX} \
	@tre         ${OUTPUTTRE}\
	>            ${OUNIT}
grep "finished successfully" ${OUNIT} > /dev/null || MDOK=0

uname -a >> ${OUNIT}

# compress some files
gzip ${OUTPUTTRX}
gzip ${OUTPUTTRE}

# copy the files back
OK=1
cp ${OUNIT}               ${SIMULDIR} || OK=0
cp ${OUTPUTCRD}           ${SIMULDIR} || OK=0
cp ${OUTPUTTRX}.gz        ${SIMULDIR} || OK=0
cp ${OUTPUTTRE}.gz        ${SIMULDIR} || OK=0

# clean up after successful run
if `test ${OK} -eq 0`; then
  uname -a > mess;
  echo 'cp failed for md_unrestrained, run 4' >> mess;
  Mail -s "ERROR" ${NAME} < mess;
  cd ${SIMULDIR};
else
  cd ${SIMULDIR};
  rm ${WORKDIR}/*;
  rmdir ${WORKDIR};
fi

# stop if MD was not succesfull
if `test ${MDOK} -eq 0`; then
  exit
fi

# perform last command (usually submit next job)
cd ${SIMULDIR}
bsub -W 4:00 -R "rusage[scratch=2000]" -n 4 -J md_unrestrained_5 -e ${SIMULDIR}/md_unrestrained_5.err -o ${SIMULDIR}/md_unrestrained_5.out < md_unrestrained_5.run 
